### ISSUE TITLE
Question_1

### ISSUE THREAD

**Issue by chartgod** [mingyang-tu/dcp-dehaze#1]
I applied dcp, but the picture comes out in black, is it correct that it came out normally? 
It's not black, but it came out very dark.

**Comment by mingyang-tu** [comment]
Yes, the results may be dark in some examples.

**Comment by chartgod** [comment]
Is there anything else that can evaluate the performance? SSIM etc

**Comment by mingyang-tu** [comment]
You can use PSNR or SSIM to evaluate performance on paired images, such as I-HAZE, O-HAZE.
